HDFS_BASE_PATH = "hdfs://namenode:9000/user/root/electricity_data"
HDFS_PARQUET_PATH = "hdfs://namenode:9000/user/root/electricity_data_parquet"
HDFS_CSV_PATH = "hdfs://namenode:9000/user/root/electricity_data_csv"
HDFS_CSV_PATH_ITA = "hdfs://namenode:9000/user/root/electricity_data_csv/IT.csv"
HDFS_CSV_PATH_SWE = "hdfs://namenode:9000/user/root/electricity_data_csv/SE.csv"
HDFS_BASE_RESULT_PATH_Q1 = "hdfs://namenode:9000/user/root/result/query1/"
HDFS_BASE_RESULT_PATH_Q2 = "hdfs://namenode:9000/user/root/result/query2/"
HDFS_BASE_RESULT_PATH_Q3 = "hdfs://namenode:9000/user/root/result/query3/"
HDFS_BASE_RESULT_PATH_Q3_EXACT = "hdfs://namenode:9000/user/root/result/query3exact/"
HDFS_BASE_RESULT_PATH_Q1_SQL = "hdfs://namenode:9000/user/root/result/query1sql/"
HDFS_BASE_RESULT_PATH_Q2_SQL = "hdfs://namenode:9000/user/root/result/query2sql/"
HDFS_BASE_RESULT_PATH_Q3_SQL = "hdfs://namenode:9000/user/root/result/query3sql/"
HDFS_BASE_RESULT_PATH_Q1_RDD = "hdfs://namenode:9000/user/root/result/query1rdd/"
HDFS_BASE_RESULT_PATH_Q2_RDD = "hdfs://namenode:9000/user/root/result/query2rdd/"
HDFS_BASE_RESULT_PATH_Q3_RDD = "hdfs://namenode:9000/user/root/result/query3rdd/"
HDFS_CSV_TOTAL_PATH = "hdfs://namenode:9000/user/root/electricity_data_csv_total"
QUERY_1_PARQUET = 1
QUERY_1_CSV = 11
QUERY_2_PARQUET = 2
QUERY_2_CSV = 12
QUERY_3_PARQUET = 3
QUERY_3_CSV = 13
QUERY_3_EXACT_PARQUET = 4
QUERY_3_EXACT_CSV = 14
QUERY_1_SQL_PARQUET = 5
QUERY_1_SQL_CSV = 15
QUERY_2_SQL_PARQUET = 6
QUERY_2_SQL_CSV = 16
QUERY_3_SQL_PARQUET = 7
QUERY_3_SQL_CSV = 17
QUERY_1_RDD = 8
QUERY_2_RDD = 9
QUERY_3_RDD = 10

SCHEMA_QUERY_1_RDD = ["Country", "record_year", "avg_carbon_intensity", "min_carbon_intensity",
                      "max_carbon_intensity", "avg_cfe_percentage", "min_cfe_percentage", "max_cfe_percentage"]
SCHEMA_QUERY_2_RDD = ["record_year", "record_month", "avg_carbon_intensity", "avg_cfe_percentage"]
SCHEMA_QUERY_3_RDD = ["country", "data", "min", "25-perc", "50-perc", "75-perc", "max"]
