HDFS_BASE_PATH = "hdfs://namenode:9000/electricity_data"
COUNTRIES = ["IT", "SE"]
YEARS = ["2021", "2022", "2023", "2024"]
HDFS_PARQUET_PATH = "hdfs://namenode:9000/electricity_data_parquet"
HDFS_BASE_RESULT_PATH_Q1 = "hdfs://namenode:9000/electricity_data_Q1_results/"
HDFS_BASE_RESULT_PATH_Q2 = "hdfs://namenode:9000/electricity_data_Q2_results/"
HDFS_BASE_RESULT_PATH_Q3 = "hdfs://namenode:9000/electricity_data_Q3_results/"
RESULTS_CSV = "/app/benchmark/execution_time.csv"
HDFS_CSV_TOTAL_PATH = "hdfs://namenode:9000/electricity_data_csv_total"
QUERY_1 = 1
QUERY_2 = 2
QUERY_3 = 3
QUERY_1_SQL = 4
